name: neuromorpho-binder
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - ipython
  - jupyterlab             # utile si on ouvre le notebook en Binder/Lab
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - umap-learn
  - morphio                # dispo conda-forge
  - pip
  - pip:
      - neurom             # via pip, plus simple que conda ici
      - morphopy
      - navis
      - ipywidgets         # widgets côté navigateur (Thebe charge html-manager)
      - -e .
