name: NeuroMorpho_ML_Pipeline
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - black
  - flake8
  - isort
  - pytest
  - neurom
  - morphio
  - morphopy
  - navis
  - umap-learn
  - scikit-learn
  - pytorch
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - numpy

  - pip:
    - python-dotenv
    - mkdocs
    - mkdocs-material
    - mkdocs-jupyter
    - -e .