name: build-book
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install jupyter-book ghp-import
      - run: jupyter-book build docs
      - run: ghp-import -n -p -f docs/_build/html
